### ISSUE TITLE
Default styling and roadmap

### ISSUE THREAD

**Issue by danieltanych** [vino46/nextjs_boilerplate#1]
**Greetings traveller!** Thanks for you boilerplate. I have a couple of questions. 
And here is one of them. As far as i know, stylus a piece of shit. So why are you dont use something else? And last one. What your roadmap about this repo?

**Thank you in advance (level of english LOL)!**

**Comment by vino46** [comment]
Hi, Dan! Appreciate your issue report, thanks a lot. 

First of all, I think that your message about stylus is an accounting for taste. Nevertheless, I’m going to create another one branch with scss for preprocessing your style. 

There will also be another branches with another features as well (typescript e.g.). 
Is this an answer to your “roadmap” question?
